---
- name: create oc {{ projectname }}
  command: oadm new-project {{ projectname }} --node-selector="site={{ ocpenv }}"

- name: Add user to project
  command: oc policy add-role-to-user admin {{ username }} -n {{ projectname }}

- name: Create postgres application for {{ username }}
  command: oc new-app --template=mongodb-persistent -p MONGODB_USER={{ dbuser }} -p MONGODB_PASSWORD={{ dbpass }} -p MONGODB_DATABASE={{ dbname }} -p VOLUME_CAPACITY={{ dbsize }}Gi -p DATABASE_SERVICE_NAME={{ dbuser }}-mongodb -p MONGODB_VERSION={{ dbver }} -n {{ projectname }}
